measure: farmer
filters:
- created_at
dimensions:
- created_at
- key: status
chart:
  type: line
  options:
    scales:
      xAxes:
      - scaleLabel:
          display: true
          labelString: Registration Date
      valueSeparator: ','
    thousands: ','